config/routes.rb
Rails.application.routes.draw do
  resources :registrations

  resources :lockers

  resources :organizations
  
  resources :application

   root 'application#index'

end

app/models/locker.rb
class Locker < ActiveRecord::Base

	belongs_to :registration
	belongs_to :organization
	validates :lockerNumber, presence: true
	validates :location, presence: true
	validates :type, presence: true
	validates :combo, presence: true
	
	class KeyedLocker < Locker 

	end

	class CodedLocker < Locker
		def combo
		end
	end
end

app/controllers/lockers_controller.rb
class LockersController < ApplicationController
  before_action :set_locker, only: [:show, :edit, :update, :destroy]

  # GET /lockers
  # GET /lockers.json
  def index
    @lockers = Locker.all
  end

  # GET /lockers/1
  # GET /lockers/1.json
  def show
  end

  # GET /lockers/new
  def new
    @locker = Locker.new
  end

  # GET /lockers/1/edit
  def edit
  end

  # POST /lockers
  # POST /lockers.json
  def create
    @locker = Locker.new(locker_params)

    respond_to do |format|
      if @locker.save
        format.html { redirect_to @locker, notice: 'Locker was successfully created.' }
        format.json { render :show, status: :created, location: @locker }
      else
        format.html { render :new }
        format.json { render json: @locker.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lockers/1
  # PATCH/PUT /lockers/1.json
  def update
    respond_to do |format|
      if @locker.update(locker_params)
        format.html { redirect_to @locker, notice: 'Locker was successfully updated.' }
        format.json { render :show, status: :ok, location: @locker }
      else
        format.html { render :edit }
        format.json { render json: @locker.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lockers/1
  # DELETE /lockers/1.json
  def destroy
    @locker.destroy
    respond_to do |format|
      format.html { redirect_to lockers_url, notice: 'Locker was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_locker
      @locker = Locker.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def locker_params
      params.require(:locker).permit(:lockerNumber, :location, :type, :combo)
    end
end

app/helpers/lockers_helper.rb
module LockersHelper
end

app/views/lockers/_form.html.erb
<%= form_for(@locker) do |f| %>
  <% if @locker.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@locker.errors.count, "error") %> prohibited this locker from being saved:</h2>

      <ul>
      <% @locker.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :lockerNumber %><br>
    <%= f.number_field :lockerNumber %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :type %><br>
    <%= f.text_field :type %>
  </div>
  <div class="field">
    <%= f.label :combo %><br>
    <%= f.number_field :combo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lockers/edit.html.erb
<h1>Editing locker</h1>

<%= render 'form' %>

<%= link_to 'Show', @locker %> |
<%= link_to 'Back', lockers_path %>

app/views/lockers/index.html.erb
<h1>Listing lockers</h1>

<table>
  <thead>
    <tr>
      <th>Lockernumber</th>
      <th>Location</th>
      <th>Type</th>
      <th>Combo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lockers.each do |locker| %>
      <tr>
        <td><%= locker.lockerNumber %></td>
        <td><%= locker.location %></td>
        <td><%= locker.type %></td>
        <td><%= locker.combo %></td>
        <td><%= link_to 'Show', locker %></td>
        <td><%= link_to 'Edit', edit_locker_path(locker) %></td>
        <td><%= link_to 'Destroy', locker, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Locker', new_locker_path %>

app/views/lockers/new.html.erb
<h1>New locker</h1>

<%= render 'form' %>

<%= link_to 'Back', lockers_path %>

app/views/lockers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lockernumber:</strong>
  <%= @locker.lockerNumber %>
</p>

<p>
  <strong>Location:</strong>
  <%= @locker.location %>
</p>

<p>
  <strong>Type:</strong>
  <%= @locker.type %>
</p>

<p>
  <strong>Combo:</strong>
  <%= @locker.combo %>
</p>

<%= link_to 'Edit', edit_locker_path(@locker) %> |
<%= link_to 'Back', lockers_path %>